// <auto-generated />
using System;
using BlazorPoultryDashboard.Application.Database.SQLCe;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorPoultryDashboard.Migrations
{
    [DbContext(typeof(BirdDbContext))]
    [Migration("20240220120607_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("BlazorPoultryDashboard.Models.Bird", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DropOff")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DropOffDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DropOffShackleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GradeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GradeShackleId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TracingId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("WeightDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeightShackleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Birds");
                });

            modelBuilder.Entity("BlazorPoultryDashboard.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageWeightRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("MeanGrade")
                        .HasColumnType("REAL");

                    b.Property<double>("MedianWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("MinWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalWeightChange")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
